# ── Server ────────────────────────────────────────────────────
server.port=8080
# ── SQL LITE  Database ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.mvgaxleoayfqbvidmlwz
spring.datasource.password=postgrescinedb

## ── H2 Console (http://localhost:8080/h2-console) ─────────────
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ── Schema & Data initialization ──────────────────────────────
spring.sql.init.mode=never
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

# ── Jackson ───────────────────────────────────────────────────
#spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ── Logging ───────────────────────────────────────────────────
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.cinema=DEBUG
springdoc.api-docs.path=/api-docs
